# Generated by Django 5.0.3 on 2024-03-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atualizado',
            name='Tamanho_Arquivo',
            field=models.CharField(default='exit', max_length=10),
            preserve_default=False,
        ),
    ]
