# Generated by Django 5.0.3 on 2024-03-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_atualizado_processo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizado',
            name='Processo',
            field=models.CharField(max_length=200),
        ),
    ]
