# Generated by Django 5.0.3 on 2024-03-26 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_alter_atualizado_processo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atualizado',
            old_name='Atualizado_Hoje',
            new_name='Atualizado_Vigente',
        ),
    ]
