# Generated by Django 5.0.3 on 2024-03-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_rename_atualizado_hoje_atualizado_atualizado_vigente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizado',
            name='Ultima_Atualizacao',
            field=models.DateField(),
        ),
    ]
