# Generated by Django 5.0.3 on 2024-03-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Processo', models.CharField(max_length=200)),
                ('Pasta', models.CharField(blank=True, max_length=200)),
                ('Atualizacao', models.CharField(choices=[('Diário', 'Diário'), ('Mensal', 'Mensal')], default='Mensal', max_length=10)),
                ('Descricao', models.TextField(blank=True)),
            ],
        ),
    ]
