# Generated by Django 5.0.3 on 2024-03-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='Atualizacao',
            field=models.CharField(choices=[('Diário', 'Diário'), ('Mensal', 'Mensal'), ('Semanal', 'Semanal'), ('Anual', 'Anual')], default='Mensal', max_length=10),
        ),
    ]
